[project]
name = "feadme"
version = "0.2.0"
description = "Fast Elliptical Accretion Disk Modeling Engine"
readme = "README.md"
authors = [
    { name = "Nicholas Earl", email = "contact@nicholasearl.me" }
]
requires-python = ">=3.13"
dependencies = [
    "arviz[h5netcdf,matplotlib]>=1.0.0",
    "astropy>=7.2.0",
    "black>=26.1.0",
    "corner>=2.2.3",
    "dacite>=1.9.2",
    "dill>=0.4.1",
    "flax>=0.12.3",
    "ipykernel>=7.2.0",
    "jax<0.10.0,>=0.8.3",
    "jaxlib<0.10.0,>=0.8.3",
    "loguru>=0.7.3",
    "matplotlib>=3.10.8",
    "multiprocess>=0.70.19",
    "numpyro",
    "quadax>=0.2.11",
    "seaborn>=0.13.2",
    "tabulate>=0.9.0",
]

[project.optional-dependencies]
gpu = ["jax[cuda12]"]

[project.scripts]
feadme = "feadme.cli:cli"

[build-system]
requires = ["uv_build>=0.9.30,<0.10.0"]
build-backend = "uv_build"
